# Obtener todos los tracks
GET http://localhost:3000/api/tracks HTTP/1.1

# Obtener un track por ID (cambia el ID por uno válido)
###
GET http://localhost:3000/api/tracks/67c8251fe1cf92e21a326dcf HTTP/1.1

# Crear un nuevo track
###
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json

{
    "name": "Nuevo Track",
    "album": "Álbum Ejemplo",
    "cover": "https://example.com/image.jpg",
    "artist": {
        "name": "Artista Ejemplo",
        "nickname": "El Crack",
        "nationality": "ES"
    },
    "duration": {
        "start": 0,
        "end": 210
    },
    "mediaId": "65f1a27a3d1eaf001b2cd000"
}

# Actualizar un track (cambia el ID)
###
PUT http://localhost:3000/api/tracks/67c8251fe1cf92e21a326dcf HTTP/1.1
Content-Type: application/json

{
    "name": "Track Actualizado"
}

# Eliminar un track (Soft Delete)
###
DELETE http://localhost:3000/api/tracks/67c8251fe1cf92e21a326dcf HTTP/1.1
